name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [ 12 ]
    steps:
      - name: Checkout Commit
      uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
      - name: Run test
      run: |
        npm run test:unit
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [12]
    needs: [unit-test]
    steps:
      - name: Checkout Commit
      uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
        - name: Run build
      run: |
        npm run build:prod
